### ISSUE TITLE
Support Eslint 8

### ISSUE THREAD

**Issue by CarsonF** [garronej/eslint-plugin-tss-unused-classes#2]
It's working fine for me with eslint v8, but I'm getting a peer dependency warning. Can you update supported version to include v8?

**Comment by chengjiaapraamcos** [comment]
@garronej bro could you look into this? we need eslint 8 working with our project. Many thanks :)

**Comment by garronej** [comment]
Sorry I miss this issue. I will address it.

**Comment by garronej** [comment]
@chengjiaapraamcos  @CarsonF,  
It's done, thanks for reporting!

**Comment by chengjiaapraamcos** [comment]
> @chengjiaapraamcos @CarsonF, It's done, thanks for reporting!

@garronej many thanks for your effort, you are the legend!
